import { Breadcrumbs, Button, Typography } from "@mui/material";
import { Link } from "react-router-dom";
import EastIcon from "@mui/icons-material/East";
import HouseOutlinedIcon from "@mui/icons-material/HouseOutlined";
import { useCartStore } from "../store/cart";
import { useEffect } from "react";

export default function OrderPlacedPage() {
  const { resetCart } = useCartStore();

  useEffect(() => {
    const timer = setTimeout(() => {
      resetCart();
    }, 3000);

    // Cleanup function to clear the
    return () => clearTimeout(timer);
  }, []);

  return (
    <>
      <section className="py-4">
        <Breadcrumbs separator=">" aria-label="breadcrumb">
          <Link className="border-b border-black" color="inherit" to="/">
            Home
          </Link>

          <Typography color="text.primary">Order is placed</Typography>
        </Breadcrumbs>
      </section>

      <section className="myContainer py-8 flex flex-col md:w-[70%] lg:w-[60%] w-[90%] justify-center items-center text-center h-full">
        <h1 className="font-bold text-lg my-2">Your request has been successfully completed</h1>
        <p className="text-gray-500">
          This text is an example of text that can be replaced in the same space. This text was
          generated by the Arabic text generator, where you can generate similar text or many other
          texts in addition to increasing the number of characters generated by the application.
        </p>
        <div className="flex justify-between items-center my-4 w-full gap-5">
          <Button
            variant="contained"
            className={"w-full shadow-none !bg-secondary "}
            onClick={() => resetCart()}
          >
            <Link className="text-white text-sm py-1" color="inherit" to="/products">
              Browse Products <EastIcon />
            </Link>
          </Button>

          <Button
            variant="outlined"
            className={"w-full shadow-none !border-secondary"}
            onClick={() => resetCart()}
          >
            <Link className="text-secondary text-sm py-1" to="/">
              Go to home <HouseOutlinedIcon />
            </Link>
          </Button>
        </div>
      </section>
    </>
  );
}
